name: multiplayer_asteroids_client_web
description: Web client for Astroids.
version: 0.0.0+1
environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  multiplayer_asteroids_common:
    path: ../../common/
  multiplayer_asteroids_client_core:
    path: ../../client_core/
dev_dependencies:
  js: ^0.6.0
