name: multiplayer_asteroids_game_server
description: Server-side core of the Astroids game supporting multiple players.
version: 0.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  multiplayer_asteroids_common:
    path: ../common/