name: multiplayer_asteroids_common
description: Common classes for Asteroids server and clients
version: 0.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  built_value: ^6.6.0
  built_collection: ^4.2.2
dev_dependencies:
  build_runner: ^1.5.1
  built_value_generator: ^6.6.0